=== onap/cps/cps-events/src/main/resources/schemas/cps-async-request-response-event-schema.json
{
  "$schema": "https://json-schema.org/draft/2019-09/schema",
  "$id": "urn:cps:org.onap.cps:async-request-response-event-schema:v1",
  "$ref": "#/definitions/CpsAsyncRequestResponseEvent",
  "definitions": {

    "CpsAsyncRequestResponseEvent": {
      "description": "The payload for CPS async request response event.",
      "type": "object",
      "properties": {
        "eventId": {
          "description": "The unique id identifying the event generated by DMI. e.g. '9999' ",
          "type": "string"
        },
        "eventCorrelationId": {
          "description": "The event correlation id for auditing. e.g. 'request-009995' ",
          "type": "string"
        },
        "eventTime": {
          "description": "The time of the event. The expected format is 'yyyy-MM-dd'T'HH:mm:ss.SSSZ'. Ex: '2020-12-01T00:00:00.000+0000'  ",
          "type": "string"
        },
        "eventSource": {
          "description": "The source of the event. e.g. 'org.onap.ncmp' ",
          "type": "string"
        },
        "eventType": {
          "description": "The type of the event. e.g. 'org.onap.ncmp.async-request-response-event",
          "type": "string"
        },
        "eventSchema": {
          "description": "The event schema for async request response events. e.g. 'org.onap.ncmp:async-request-response-event:v1' ",
          "type": "string"
        },
        "eventTarget": {
          "description": "The target of the event. e.g. 'topic:client-application-topic' ",
          "type": "string"
        },
        "event": {
          "$ref": "#/definitions/Event-Content"
        }
      },
      "required": [
        "eventId",
        "eventCorrelationId",
        "eventTime",
        "eventSource",
        "eventType",
        "eventSchema",
        "eventTarget"
      ],
      "additionalProperties": true
    },

    "Event-Content": {
      "description": "The event content.",
      "type": "object",
      "properties": {
        "response-data-schema": {
          "description": "The schema of response data e.g. 'org.onap.cps.yang-patch-json:v1' ",
          "type": "string"
        },
        "response-status": {
          "description": "The status of the response. e.g. 'SUCCESS' ",
          "type": "string"
        },
        "response-code": {
          "description": "The code of the response. e.g. '200' ",
          "type": "string"
        },
        "response-data": {
          "$ref": "#/definitions/Response-Data"
        }
      },
      "required": [
        "response-data-schema",
        "response-status",
        "response-code",
        "response-data"
      ],
      "additionalProperties": true
    },
    "Response-Data": {
      "description": "Data as json object.",
      "type": "object"
    }
  }
}

=== onap/cps/cps-service/src/test/resources/cpsAsyncRequestResponseEvent.json
{
  "eventId": "9999",
  "eventCorrelationId": "request-009995",
  "eventTime": "2021-11-16T16:42:25-04:00",
  "eventSource": "org.onap.ncmp",
  "eventType": "org.onap.ncmp.async-request-response-event",
  "eventSchema": "org.onap.ncmp:async-request-response-event:v1",
  "eventTarget": "topic:client-application-topic",
  "event": {
    "response-data-schema": "org.onap.cps.yang-patch-json:v1",
    "response-status": "SUCCESS",
    "response-code": "200",
    "response-data": {"some-key": "some-value"}
  }
}
