=== onap/cps/cps-ncmp-events/src/main/resources/schemas/dmi-async-bulk-response-event-schema-v1.json
{
  "$schema": "https://json-schema.org/draft/2019-09/schema",
  "$id": "urn:cps:org.onap.cps.ncmp.events:dmi-async-bulk-response-event-schema:v1",
  "$ref": "#/definitions/DMIAsyncBulkResponseEvent",
  "definitions": {
    "DMIAsyncBulkResponseEvent": {
      "description": "The payload for bulk response event.",
      "type": "object",
      "properties": {
        "eventId": {
          "description": "The unique id identifying the event generated by DMI for this bulk response event.",
          "type": "string"
        },
        "eventTime": {
          "description": "The time of bulk response event. The expected format is 'yyyy-MM-dd'T'HH:mm:ss.SSSZ'.",
          "type": "string"
        },
        "eventTarget": {
          "description": "The target of the event.",
          "type": "string"
        },
        "event": {
          "$ref": "#/definitions/Event"
        }
      },
      "required": [
        "eventId",
        "eventTime",
        "eventTarget",
        "event"
      ]
    },
    "Event": {
      "description": "The bulk response event content.",
      "type": "object",
      "existingJavaType": "java.lang.Object"
    }
  }
}

=== onap/cps/cps-ncmp-service/src/test/resources/dmiAsyncBulkResponseEvent.json
{
  "eventId": "8dbfe0a7-3b28-4109-8fcb-9fbc9c37d56a",
  "eventTarget": "client-topic",
  "eventTime": "2022-05-09T13:34:50.466+0000",
  "event": {
    "response-data": {
      "ietf-netconf-monitoring:netconf-state": {
        "schemas": {
          "schema": [
            {
              "identifier": "ietf-tls-server",
              "version": "2016-11-02",
              "format": "ietf-netconf-monitoring:yang",
              "namespace": "urn:ietf:params:xml:ns:yang:ietf-tls-server",
              "location": [
                "NETCONF"
              ]
            }
          ]
        }
      }
    }
  }
}
